package com.laundrypro.repository;

import com.laundrypro.model.Report;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;

import java.time.LocalDateTime;
import java.util.List;

public interface ReportRepository extends JpaRepository<Report, Integer> {

    // Find reports by date range
    List<Report> findByReportDateBetween(LocalDateTime startDate, LocalDateTime endDate);

    // Find reports by time range (week, month, quarter, year)
    List<Report> findByTimeRange(String timeRange);

    // Find all reports ordered by date descending
    Page<Report> findAllByOrderByReportDateDesc(Pageable pageable);

    // Find reports by generated by user
    List<Report> findByGeneratedBy(String generatedBy);
}

